name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

concurrency:
  group: update-ip-list
  cancel-in-progress: true  # 如果有新的运行，取消旧的

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史，避免 push 被拒绝

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "tianshideyou@proton.me"
        git config --global user.name "tianshipapa"
        if [ -n "$(git status --porcelain)" ]; then
          git stash push -m "temp stash before pull"
          git pull --rebase origin main
          git stash pop
          git add ip.txt
          git commit -m "Automatic update"
          git push origin main
        else
          echo "No changes detected, skipping commit."
        fi
